// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTzrvMaip8AK6g7P-GuQCwTttOQjDluZ0',
    appId: '1:650077864825:web:35ef4403e4360095b6a5a8',
    messagingSenderId: '650077864825',
    projectId: 'cartainc-2cac0',
    authDomain: 'cartainc-2cac0.firebaseapp.com',
    storageBucket: 'cartainc-2cac0.appspot.com',
    measurementId: 'G-ZBQSN1H67S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsO2i3ULCLIjldhqoQgj6VZErNTmEqKZg',
    appId: '1:650077864825:android:47dba3f80a7f69bdb6a5a8',
    messagingSenderId: '650077864825',
    projectId: 'cartainc-2cac0',
    storageBucket: 'cartainc-2cac0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOnDL0SIavuXO1cnnKB8iQqYtJ3J5i-nc',
    appId: '1:650077864825:ios:a65d02d139cde1acb6a5a8',
    messagingSenderId: '650077864825',
    projectId: 'cartainc-2cac0',
    storageBucket: 'cartainc-2cac0.appspot.com',
    iosBundleId: 'com.example.cartaInc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOnDL0SIavuXO1cnnKB8iQqYtJ3J5i-nc',
    appId: '1:650077864825:ios:8ccfc727d152e37ab6a5a8',
    messagingSenderId: '650077864825',
    projectId: 'cartainc-2cac0',
    storageBucket: 'cartainc-2cac0.appspot.com',
    iosBundleId: 'com.example.cartaInc.RunnerTests',
  );
}
